### ISSUE TITLE
When I using deepmerge in vite project

### ISSUE THREAD

**Issue by mutoe** [mutoe/vue3-realworld-example-app#11]
When I merge the #10 , I got this error in browser and dev mode

```
Uncaught SyntaxError: import not found: default
```

It located the 1st line in `request.ts`

```ts
import merge from 'deepmerge'
^^^^^^
```

@levchak0910  Do you have any idea?

**Comment by levchak0910** [comment]
I forgot add deepmerge to package.json
It seems somewhere in development time i discarded files in my IDE and forget add this dependency again
(Shame on me)

Fixed

**Comment by mutoe** [comment]
Oh... I think it should throw "not found module xxx" it's confusing.
