### ISSUE TITLE
Methods naming

### ISSUE THREAD

**Issue by levchak0910** [mutoe/vue3-realworld-example-app#12]
@mutoe, could i ask, why do you use this kind of function namings:
v-on: something = "**on do something**" (ex.: `@update="onUpdateArticle"`)
Are there some styleguides or it is only your preference?

**Comment by mutoe** [comment]
This is just derived from the experience of naming props in React. What do you think?

**Comment by levchak0910** [comment]
I'm used to using v-on: something = "**do something**"
And I have never seen this before, in different vue apps on github, hence this question (as well as I didn't work with React)

**Comment by mutoe** [comment]
No worries, it's just my experence. Just follow your heart :)
