### ISSUE TITLE
register and login errors are not display

### ISSUE THREAD

**Issue by plumrx** [mutoe/vue3-realworld-example-app#17]
![image](https://user-images.githubusercontent.com/42860331/97591673-cf1ad680-1a3a-11eb-8c15-1ff47110f211.png)
like this one

**Comment by levchak0910** [comment]
We aware of this
Would you like to help us to implement it?

**Comment by levchak0910** [comment]
Implemented 0c097e036fc57a2663be0be6db467b42d120a3a7
