### ISSUE TITLE
Avoid using one-word name for components

### ISSUE THREAD

**Issue by levchak0910** [mutoe/vue3-realworld-example-app#23]
Respect [style guide](https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential)

**Comment by mutoe** [comment]
Ok, I'll fix it. 

But what puzzles me is why ESLint doesn't work.

https://github.com/mutoe/vue3-realworld-example-app/blob/e3a04416eaef8eaf36865adf866d448426f5d636/package.json#L71
