### ISSUE TITLE
ESLint explicit-module-boundary-types should be enable

### ISSUE THREAD

**Issue by soerenmartius** [mutoe/vue3-realworld-example-app#29]
I recommend removing `"@typescript-eslint/explicit-module-boundary-types": "off"` in package.json since it completely disables return type checking of module boundaries.

Maybe, instead of deactivating the rule globally, just use inline toggles?

```
// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
const useComposable = () => { ...
```

**Comment by levchak0910** [comment]
@soerenmartius, thanks for this hint
fixed in 7c2d0a9df3638f53fe44c690d379e89d3161a88e
