### ISSUE TITLE
Bundle size optimize

### ISSUE THREAD

**Issue by mutoe** [mutoe/vue3-realworld-example-app#39]
![image](https://user-images.githubusercontent.com/9391981/110228066-19f0b180-7f39-11eb-89e6-7bff15f1d21a.png)

**Comment by mutoe** [comment]
After replacing DOMPurify and remove deepmerge

![image](https://user-images.githubusercontent.com/9391981/110234301-b1b7c500-7f64-11eb-8b38-b1a04e7e25d1.png)

**Comment by levchak0910** [comment]
Hi @mutoe 
Are our unit tests (utils/request.spec.js) are passing after removing deepmerge?

**Comment by mutoe** [comment]
> Hi @mutoe
> Are our unit tests (utils/request.spec.js) are passing after removing deepmerge?

@levchak0910 Yep, all tests were passed in the newest CI https://github.com/mutoe/vue3-realworld-example-app/actions/runs/629130533

**Comment by levchak0910** [comment]
Ok, great work!
