### ISSUE TITLE
Getting JWT Error while update profile and create new Article.

### ISSUE THREAD

**Issue by thebleshbanz** [mutoe/vue3-realworld-example-app#64]
Hello there,

thanks for your contribution
i am new in Vuejs, for learning purpose i setuped this repo with laravel realworld backend
i am getting this error while update profile or create new article.
{"errors":{"message":"JWT error: Token is absent","status_code":401}}

Thanks

**Comment by levchak0910** [comment]
Hi @thebleshbanz 
It seems that a problem somewhere in the laravel app (I am not a PHP developer, so I can not help more accurately)
Token is sent OK from the front-end 
![1](https://user-images.githubusercontent.com/37511777/124644316-c9637380-de9a-11eb-991e-c34ffdaf6698.png)
