### ISSUE TITLE
why not just use new URLSearchParams(object).toString() ? 

### ISSUE THREAD

**Issue by orenmizr** [mutoe/vue3-realworld-example-app#65]
https://github.com/mutoe/vue3-realworld-example-app/blob/2e48d2d516940eba7e8410480ddfee76665ff913/src/utils/params-to-query.ts#L2

love reading your code btw 👍

**Comment by mutoe** [comment]
Good suggestion, I will update it later :)

**Comment by mutoe** [comment]
I found it not feasible. The `URLSearchParams` constuctor only accept `Record<string, string>`, but I need to pass in `Record<string, string | number | boolean>`

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/9391981/129471537-2d0715c4-da0d-400e-a5ae-6d9261b1cf9c.png">
